title: 安南说
subtitle: 曾经体无完肤，仍将砥砺前行！
keywords: 技术，编程，成长，心得体会
description: 安南说见证着成长，所有缺点都成为叙述的方向。作者：周筱鲁(@jiusanzhou)，网址：https://annan.tk。
author: 周筱鲁(https://annan.tk)
language:
- zh-cn
- en

timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://annan.tk
root: /
permalink: :category/:entitle-:timestamp.html
permalink_defaults:
  lang: en

# Directory
source_dir: _post
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - README.zhCN.md

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: false # Open external links in new tab
filename_case: 0s
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: 技术
category_map:
   编程: programming
   硬件: hardware
   人文: humanities
   心理: psychological
   其他: others
tag_map:
  iOS: iOS
  Android: Android
  hugo: hugo
  swift: swift
  golang: golang
  sketch: sketch
  zeplin: zeplin
  网站: website
  后端: server
  分布式: distributed
  容器: container
  服务网格: ServieMesh
  JavaScript: javascript
  TypeScript: typescript
  ReactNative: RN
  跨平台: CrossPlatform
  黑科技: CoolTech

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

sns:
  telegram: http://t.me/jiusanzhou
  instagram: https://www.instagram.com/jiusanzhou/
  twitter: https://twitter.com/jiusanzhou
  github: https://github.com/jiusanzhou
  sinaWb: https://weibo.com/jsz3

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/


theme: hexo-theme-jsimple


# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: https://nanshuo@github.com/nanshuo/nanshuo.github.io.git
  branch: master
