title: 安南说
subtitle: 曾经体无完肤，仍将砥砺前行！
keywords: 技术，编程，成长，心得体会
description: 安南说见证着成长，所有缺点都成为叙述的方向。作者：周筱鲁(@jiusanzhou)，网址：https://annan.tk。
author: 周筱鲁
language:
- zh-cn
- en

avatarImage: https://avatars1.githubusercontent.com/u/2942042?s=460&v=4
timezone:

url: https://annan.tk
root: /
permalink: :entitle-:timestamp.html
permalink_defaults:
  lang: en

# Directory
source_dir: _posts
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md

new_post_name: :year:month:day-:title.md
default_layout: post
titlecase: true # Transform title into titlecase

external_link: false # Open external links in new tab
filename_case: 0s
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace:


default_category: 技术

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 10
pagination_dir: page

theme: hexo-theme-jsimple
custom:
  leftPagesMenu:
  - uri: about
    title: 关于
    faName: fa-question-circle
  menu:
    编程: programming
    人文: humanities
    随想: thought
  sns:
    telegram: http://t.me/jiusanzhou
    instagram: https://www.instagram.com/jiusanzhou/
    twitter: https://twitter.com/jiusanzhou
    github: https://github.com/jiusanzhou
    weibo: https://weibo.com/jsz3
